/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdio.h>

/*
 * This exercise is used in order to enable the printf mechanism for debugging.
 *
 * To enable printf:
 * In the "debug configurations" (located under the "debug button's menu", int the debugger tab, select enable "serial wire viewer"
 * Add the code from here:
 * https://github.com/niekiran/Embedded-C/blob/master/All_source_codes/target/itm_send_data.c
 *
 * to syscalls.c (located in the src directory), immediately after the includes, and modifu __write frunction to call
 * ITM_SendChar()
 * instead of
 * __io_putchar()
 * (Keep the same parameters as was in use by __io_putchar())
 * In the debug perspective select window->showView->SWV->SWV-ITM data console.
 * In that console window  select configuration and then enable port 0.
 * Press on the start button of the SWV ITM Data console window and run the code with the printf.
 * prints should show on the SWV ITM console window.
 *
 */
int main(void)
{
    printf("Hello world!!! this is a beautiful day!\n");
    /* Loop forever */
	for(;;);
}
