/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdio.h>
// Steps for testing the weak/strong functions.

//1) Create a new STM32 project
//2) In the main .c use the below code
//void SPI_ApplicationEventCallback(int x, int y);
//int main(void)
//{
//SPI_ApplicationEventCallback(1,2);
//for(;;);
//}

//void SPI_ApplicationEventCallback(int x, int y)
//{
//printf("strong function\n");
//}
//3) In sysmem.c (or any other file) add below function
//__attribute__((weak)) void SPI_ApplicationEventCallback(int x, int y)
//{
//printf("weak function\n");
//}
//
//4) Build and test and you see it executes strong function
//5) Now comment out (or rename) the strong function, and the weak function will execute when called


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


void SPI_ApplicationEventCallback(int x, int y);

void SPI_ApplicationEventCallback1(int x, int y)
{
	printf("strong function\n");
}

int main(void)
{
	SPI_ApplicationEventCallback(1,2);
    /* Loop forever */
	for(;;);
}
